---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      name: static-server
      labels:
        app: static-server
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        "consul.hashicorp.com/service-meta-version": "2"
        "consul.hashicorp.com/service-tags": "v2"
    spec:
      containers:
        - name: static-server-v2
          imagePullPolicy: Never
          image: api:latest
          ports:
            - containerPort: 8787
              name: http

